### ISSUE TITLE
Is it possible to provide the ModelNet40-Partial dataset?

### ISSUE THREAD

**Issue by hankyang94** [wentaoyuan/deepgmr#1]
Hi, thanks for sharing the code and the datasets, this is a nice work.

In the supplementary material of the paper, you performed experiments on partial point cloud pairs generated from ModelNet40, I am wondering could you share that dataset as well (like what you did for ModelNet40 Clean and ModelNet40 Noisy) so that I can run other algorithms on the dataset?

Thanks!

**Comment by wentaoyuan** [comment]
Unfortunately I did not have access to the ModelNet partial data now, but the orthographic projection function is available [here](https://github.com/wentaoyuan/it-net/blob/55e654b42ae873ee19ddeb21d3a9abfc692612bd/util/data_util.py#L47). You can generate partial point clouds by passing complete point clouds to the function. You might need to tweak the [image dimension](https://github.com/wentaoyuan/it-net/blob/55e654b42ae873ee19ddeb21d3a9abfc692612bd/util/data_util.py#L57) and [camera intrinsics](https://github.com/wentaoyuan/it-net/blob/55e654b42ae873ee19ddeb21d3a9abfc692612bd/util/data_util.py#L60).
