### ISSUE TITLE
Error calculation in the process of evaluating model

### ISSUE THREAD

**Issue by fukexue** [wentaoyuan/deepgmr#2]
When I run the code again, I have some confusion. Here is my personal opinion:
In my opinion, there are some problems in the calculation of errors, which are as follows:
```
class DeepGMR(nn.Module):
    def __init__(self, args):
       ....
    def regis_err(self, T_gt, reverse=False):
       ....
        self.r_err = rotation_error( self.T_12[:3, :3], T_gt[:3, :3] )
        self.t_err = translation_error(self.T_12[:3, 3], T_gt[:3, 3])
        self.rmse = rmse(self.pts1[:, :100], self.T_12, T_gt)
```
I think the bold text should be calculated as follows:
```
   self.r_err = rotation_error(self.T_12[:, :3, :3], T_gt[:, :3, :3])
   self.t_err = translation_error(self.T_12[:, :3, 3], T_gt[:, :3, 3])
```

At the same time, I think the following calculation also has problems:

```
def evaluate(model, loader, save_results=False, results_dir=None):
       for step, (pts1, pts2, T_gt) in enumerate(tqdm(loader, leave=False)):
        ...
            N += pts1.shape[0]
        start = time()
        with torch.no_grad():
            loss, r_err, t_err, rmse = model(pts1, pts2, T_gt)
            inference_time += time() - start

        losses += loss.item()
        r_errs += r_err.mean().item()
        t_errs += t_err.mean().item()
        rmses += rmse.mean().item()
    ...
    log_str = log_fmt.format(
        inference_time / N, preprocess_time / N,
        losses / N, r_errs / N, t_errs / N, rmses / N
    )
```

I don't think we should divide by N at the end. Because the previous calculation has averaged the error of each batch. So this should be divided by the final step number. Or use the one you used in the previous training np.mean Methods.
If there are any mistakes, please criticize and correct them

**Comment by wentaoyuan** [comment]
These are indeed some errors introduced while cleaning up the code. Thanks for spotting that out! I've fixed them. I also checked the original code that generated the results in the paper and they are correct, so the numbers in the paper are reliable.
