### ISSUE TITLE
Is it possible to provide the ModelNet unseen dataset?

### ISSUE THREAD

**Issue by Zayes** [wentaoyuan/deepgmr#5]
Hi, I’m interested in your great work.Thanks for sharing the code and the datasets.

I want to reproduce your results, but when I follow the readme file and download data to train the model on ModelNet unseen, I could not find the ‘modelnet20.h5’. I return to the download link and make sure that the ‘modelnet20.h5’ is not in the ‘data/train’ fold. I am wondering could you share that dataset as well?

Thanks a lot!

**Comment by wentaoyuan** [comment]
Hi, I've just uploaded `modelnet20.h5` and you should be able to find it in `data/train`.
